// Parse coverage of ingredient lines across all recipes.
// Usage (from the repo root): node scripts/coverage.js [--out review/coverage.md]
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const U = require('../recipes/assets/js/units.js');

const root = path.resolve(__dirname, '..');
const yamlPath = path.join(root, 'recipes/_data/ingredients.yml');
const json = execFileSync('ruby', ['-ryaml', '-rjson', '-rdate', '-e', 'puts JSON.generate(YAML.safe_load(File.read(ARGV[0]), permitted_classes: [Date]))', yamlPath]);
const ingredients = U.prepareIngredients(JSON.parse(json));

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return e.name.startsWith('_') ? [] : walk(p);
    return e.name.endsWith('.md') ? [p] : [];
  });
}

const rows = [];
for (const file of walk(path.join(root, 'recipes')).sort()) {
  const src = fs.readFileSync(file, 'utf8');
  for (const block of src.matchAll(/<div class="ingredients"[^>]*>([\s\S]*?)<\/div>/g)) {
    for (const raw of block[1].split('\n')) {
      const m = raw.match(/^\s*[-*]\s+(.*)$/);
      if (!m) continue;
      const p = U.parseLine(m[1], ingredients);
      let cls;
      if (!p.qty) cls = 'no amount';
      else if (p.dim === 'count' || p.dim === 'stick') cls = 'count (left alone)';
      else if (!p.ingredient) cls = `${p.dim}, no ingredient match`;
      else if (p.dim === 'volume' && !p.ingredient.gramsPerTsp) cls = 'volume, ingredient has no density';
      else if (p.dim === 'weight' && !p.ingredient.gramsPerTsp) cls = 'weight, no density (weight-only is fine)';
      else cls = `${p.dim}, convertible`;
      const w = U.render(p, 'weight', 1);
      const v = U.render(p, 'volume', 1);
      rows.push({ file: path.relative(path.join(root, 'recipes'), file), text: m[1], cls, ing: p.ingredient ? p.ingredient.id : '', weight: w.changed ? w.amount : '', volume: v.changed ? v.amount : '' });
    }
  }
}

const counts = {};
for (const r of rows) counts[r.cls] = (counts[r.cls] || 0) + 1;
const measured = rows.filter(r => /^(volume|weight|stick)/.test(r.cls));
const convertible = rows.filter(r => /convertible/.test(r.cls));

let md = `# Parse coverage\n\nGenerated by \`node scripts/coverage.js\`.\n\n`;
md += `- Ingredient lines: **${rows.length}**\n`;
md += `- Lines with a volume or weight amount: **${measured.length}**\n`;
md += `- Of those, convertible (amount + unit + ingredient with a density): **${convertible.length}** (${Math.round((100 * convertible.length) / measured.length)}%)\n\n`;
md += `| Class | Lines |\n|---|---|\n`;
for (const [k, n] of Object.entries(counts).sort((a, b) => b[1] - a[1])) md += `| ${k} | ${n} |\n`;
md += `\n## Every line\n\n| File | Line | Class | Ingredient | Weights mode | Volumes mode |\n|---|---|---|---|---|---|\n`;
const esc = s => String(s).replace(/\|/g, '\\|');
for (const r of rows) md += `| ${r.file} | ${esc(r.text)} | ${r.cls} | ${r.ing} | ${esc(r.weight)} | ${esc(r.volume)} |\n`;

const outIdx = process.argv.indexOf('--out');
if (outIdx > -1) {
  fs.writeFileSync(path.resolve(process.argv[outIdx + 1]), md);
  console.log(`wrote ${process.argv[outIdx + 1]}`);
}
console.log(md.split('## Every line')[0]);
