// Parse coverage of ingredient lines, and the canonical "weight (volume)" form of each.
// Usage (from the repo root):
//   node scripts/coverage.js [--out review/coverage.md]
//   node scripts/coverage.js --apply recipes/pastry/choux.md [more files...]   rewrite those files in place
const fs = require('fs');
const path = require('path');
const { execFileSync } = require('child_process');
const U = require('../recipes/assets/js/units.js');

const root = path.resolve(__dirname, '..');
const yamlPath = path.join(root, 'recipes/_data/ingredients.yml');
const json = execFileSync('ruby', ['-ryaml', '-rjson', '-rdate', '-e', 'puts JSON.generate(YAML.safe_load(File.read(ARGV[0]), permitted_classes: [Date]))', yamlPath]);
const ingredients = U.prepareIngredients(JSON.parse(json));

function walk(dir) {
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap(e => {
    const p = path.join(dir, e.name);
    if (e.isDirectory()) return e.name.startsWith('_') ? [] : walk(p);
    return e.name.endsWith('.md') ? [p] : [];
  });
}

const LIST_ITEM = /^(\s*[-*]\s+)(.*)$/;

function classify(p) {
  if (!p.qty) return 'no amount';
  if (p.dim === 'count' || p.dim === 'stick') return 'count (left alone)';
  if (!p.ingredient) return `${p.dim}, no ingredient match`;
  if (!p.ingredient.gramsPerTsp) return `${p.dim}, ingredient has no density`;
  return `${p.dim}, convertible`;
}

// Rewrite ingredient blocks in one file; returns [{before, after}] for changed lines.
function rewrite(src) {
  const changes = [];
  const out = src.replace(/(<div class="ingredients"[^>]*>)([\s\S]*?)(<\/div>)/g, (all, open, body, close) => {
    const lines = body.split('\n').map(line => {
      const m = line.match(LIST_ITEM);
      if (!m) return line;
      const after = U.canonical(U.parseLine(m[2], ingredients));
      if (!after || after === m[2]) return line;
      changes.push({ before: m[2], after });
      return m[1] + after;
    });
    return open + lines.join('\n') + close;
  });
  return { out, changes };
}

const applyIdx = process.argv.indexOf('--apply');
if (applyIdx > -1) {
  for (const f of process.argv.slice(applyIdx + 1)) {
    const file = path.resolve(f);
    const { out, changes } = rewrite(fs.readFileSync(file, 'utf8'));
    fs.writeFileSync(file, out);
    console.log(`${f}: ${changes.length} line(s) rewritten`);
    for (const c of changes) console.log(`  - ${c.before}\n  + ${c.after}`);
  }
  process.exit(0);
}

const rows = [];
for (const file of walk(path.join(root, 'recipes')).sort()) {
  const src = fs.readFileSync(file, 'utf8');
  for (const block of src.matchAll(/<div class="ingredients"[^>]*>([\s\S]*?)<\/div>/g)) {
    for (const raw of block[1].split('\n')) {
      const m = raw.match(LIST_ITEM);
      if (!m) continue;
      const p = U.parseLine(m[2], ingredients);
      rows.push({ file: path.relative(path.join(root, 'recipes'), file), text: m[2], cls: classify(p), ing: p.ingredient ? p.ingredient.id : '', canonical: U.canonical(p) || '' });
    }
  }
}

const counts = {};
for (const r of rows) counts[r.cls] = (counts[r.cls] || 0) + 1;
const measured = rows.filter(r => /^(volume|weight)/.test(r.cls));
const convertible = rows.filter(r => /convertible/.test(r.cls));
const changed = rows.filter(r => r.canonical);

let md = `# Parse coverage and canonical form\n\nGenerated by \`node scripts/coverage.js\`.\n\n`;
md += `- Ingredient lines: **${rows.length}**\n`;
md += `- Lines with a volume or weight amount: **${measured.length}**\n`;
md += `- Of those, convertible: **${convertible.length}** (${Math.round((100 * convertible.length) / measured.length)}%)\n`;
md += `- Lines the canonical form would change: **${changed.length}** across **${new Set(changed.map(r => r.file)).size}** recipes\n\n`;
md += `| Class | Lines |\n|---|---|\n`;
for (const [k, n] of Object.entries(counts).sort((a, b) => b[1] - a[1])) md += `| ${k} | ${n} |\n`;
md += `\n## Proposed canonical lines, by recipe\n\nOnly lines that would change. Apply to a recipe with \`node scripts/coverage.js --apply recipes/<path>.md\`.\n`;
const esc = s => String(s).replace(/\|/g, '\\|');
let current = null;
for (const r of changed) {
  if (r.file !== current) { md += `\n### ${r.file}\n\n| Now | Canonical |\n|---|---|\n`; current = r.file; }
  md += `| ${esc(r.text)} | ${esc(r.canonical)} |\n`;
}
md += `\n## Every line\n\n| File | Line | Class | Ingredient |\n|---|---|---|---|\n`;
for (const r of rows) md += `| ${r.file} | ${esc(r.text)} | ${r.cls} | ${r.ing} |\n`;

const outIdx = process.argv.indexOf('--out');
if (outIdx > -1) {
  fs.writeFileSync(path.resolve(process.argv[outIdx + 1]), md);
  console.log(`wrote ${process.argv[outIdx + 1]}`);
}
console.log(md.split('## Proposed')[0]);
